### ISSUE TITLE
remove google analytics tag

### ISSUE THREAD

**Issue by kblincoe** [sharmapn/sharmapn.github.io#1]
Hey, great website! Can you update the _includes/google_analytics.html file to remove my google analytics tag (just noticed my analytics includes some visits to your website). You can add your own tag there or just remove that file (and it's reference in _includes/header.html). Thanks!

**Comment by sharmapn** [comment]
Thanks and No problem, Kelly,
I will remove the tag by Monday.
Cheers,
Pankaj

**Comment by sharmapn** [comment]
Morning Kelly,

Commented that line, as shown.

[image: image.png]


Cheers,
Pankaj

**Comment by sharmapn** [comment]
Oh, and this line as well.

[image: image.png]

**Comment by kblincoe** [comment]
Thanks!
